#ifndef MAGIC_CONFIG_H
#define MAGIC_CONFIG_H

#define MGCD_DEBUG_TOKENIZER 0
#define MGCD_DEBUG_JOBS 0
#define MGCD_DEBUG_CHUNK_CACHE 1

#define MGC_CHUNK_CACHE_SIZE (8*8*8)

#define CHUNK_WIDTH 16
#define CHUNK_HEIGHT 16
#define CHUNK_LAYER_NUM_TILES (CHUNK_WIDTH*CHUNK_WIDTH)
#define CHUNK_NUM_TILES (CHUNK_LAYER_NUM_TILES*CHUNK_HEIGHT)

#endif
