#ifndef MAGIC_CONFIG_H
#define MAGIC_CONFIG_H

#define MGCD_DEBUG_TOKENIZER 0
#define MGCD_DEBUG_JOBS 0
#define MGCD_DEBUG_CHUNK_CACHE 0

#define MGC_SIM_RADIUS 64
#define MGC_SIM_SKIRT_RADIUS 32

#define LOG_CHUNK_WIDTH 5
#define LOG_CHUNK_HEIGHT 5
#define CHUNK_WIDTH (1<<(LOG_CHUNK_WIDTH))
#define CHUNK_HEIGHT (1<<(LOG_CHUNK_HEIGHT))
#define CHUNK_LAYER_NUM_TILES (CHUNK_WIDTH*CHUNK_WIDTH)
#define CHUNK_NUM_TILES (CHUNK_LAYER_NUM_TILES*CHUNK_HEIGHT)

#define RENDER_CHUNK_WIDTH 32
#define RENDER_CHUNK_HEIGHT 32
#define RENDER_CHUNK_LAYER_NUM_TILES (RENDER_CHUNK_WIDTH*RENDER_CHUNK_WIDTH)
#define RENDER_CHUNK_NUM_TILES (RENDER_CHUNK_LAYER_NUM_TILES*RENDER_CHUNK_HEIGHT)

#if (CHUNK_WIDTH % RENDER_CHUNK_WIDTH) != 0
#error "RENDER_CHUNK_WIDTH must be a multiple of CHUNK_WIDTH"
#endif

#if (CHUNK_HEIGHT % RENDER_CHUNK_HEIGHT) != 0
#error "RENDER_CHUNK_HEIGHT must be a multiple of CHUNK_HEIGHT"
#endif

#define RENDER_CHUNKS_PER_CHUNK_WIDTH (CHUNK_WIDTH/RENDER_CHUNK_WIDTH)
#define RENDER_CHUNKS_PER_CHUNK_HEIGHT (CHUNK_HEIGHT/RENDER_CHUNK_HEIGHT)
#define RENDER_CHUNKS_PER_CHUNK_LAYER (RENDER_CHUNKS_PER_CHUNK_WIDTH*RENDER_CHUNKS_PER_CHUNK_WIDTH)
#define RENDER_CHUNKS_PER_CHUNK (RENDER_CHUNKS_PER_CHUNK_LAYER*RENDER_CHUNKS_PER_CHUNK_HEIGHT)

#define SIM_CHUNK_BATCH_SIZE_LAYERS 8
#if (CHUNK_HEIGHT % SIM_CHUNK_BATCH_SIZE_LAYERS) != 0
#error "SIM_CHUNK_BATCH_SIZE_LAYERS must be a multiple of CHUNK_HEIGHT"
#endif

#define NUM_SIM_CHUNKS_WIDTH (((MGC_SIM_RADIUS*2+1 + CHUNK_WIDTH-1)/CHUNK_WIDTH)+1)
#define NUM_SIM_CHUNKS_HEIGHT (((MGC_SIM_RADIUS*2+1 + CHUNK_HEIGHT-1)/CHUNK_HEIGHT)+1)
#define NUM_SIM_CHUNKS (NUM_SIM_CHUNKS_WIDTH*NUM_SIM_CHUNKS_WIDTH*NUM_SIM_CHUNKS_HEIGHT)


#define HEX_HEIGHT (0.25f)
#define HEX_RADIUS (0.5f)

#define MGC_CHUNK_CACHE_WIDTH (10)
#define MGC_CHUNK_CACHE_SIZE (MGC_CHUNK_CACHE_WIDTH*MGC_CHUNK_CACHE_WIDTH*MGC_CHUNK_CACHE_WIDTH)


#endif
